#input {
#  file {
#    path => "/var/log/apache2/access.log"
#    start_position => "beginning"
#  }
#}

#input {
#  pipe {
#      command => "tail -f /var/log/apache2/access.log"
#      codec => plain {
#         charset => "ISO-8859-1"
#      }
#  }
#}

input {
  tcp {
    port => 5000
    type => "apache_access_log"
  }
  tcp {
    port => 5001
    type => "apache_error_log"
  }
}

filter {
  if [type] == "apache_access_log" {
    grok {
      match => { "message" => "%{HOSTNAME:nodename} %{IP:nodeip} %{COMBINEDAPACHELOG}" }
    }
  }
  date {
    match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
    locale => "en"
  }
  geoip {
    source => "clientip"
    target => "geoip"
    database => "/mnt/data/src/bitbucket.org/infrared/logstash/vendor/geoip/GeoLiteCity.dat"
    add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
    add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
  }

  if ([type] == "apache_error_log") {

    grok {
      patterns_dir => [ "/mnt/data/src/bitbucket.org/infrared/logstash/patterns/apache-error" ]
      match => [ "message", "%{HOSTNAME:nodename} %{IP:nodeip} %{APACHE_ERROR_LOG}" ]
    }

    date {
      match => [ "timestamp" , "EEE MMM d HH:mm:ss.SSSSSS yyyy" ]
      locale => "en"
    }
  }
}

output {
  elasticsearch { hosts => ["localhost:9200"] }
  stdout { codec => json }
}