input {
  stdin{}
}

filter {
  grok {
    match => { "message" => "%{HTTPDERROR_DATE:timestamp}" }
  }

  date {
    locale => "en"
    match => [ "timestamp" , "EEE MMM d HH:mm:ss.SSSSSS yyyy" ]
    add_field => { "debug" => "timestampMatched"}
  }
}

#%{DAY} %{MONTH} %{MONTHDAY} %{TIME} %{YEAR}

output {
  stdout {
    codec => "rubydebug"
  }
}